"""empty message

Revision ID: d03153f5d9a9
Revises: 
Create Date: 2019-04-08 17:14:56.215427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03153f5d9a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('employee', 'full_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_employee_full_name'), 'employee', ['full_name'], unique=False)
    op.create_index(op.f('ix_employee_manager_id'), 'employee', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employee_position'), 'employee', ['position'], unique=False)
    op.create_index(op.f('ix_employee_salary'), 'employee', ['salary'], unique=False)
    op.create_index(op.f('ix_employee_work_start'), 'employee', ['work_start'], unique=False)
    op.drop_constraint('employees_id_key', 'employee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('employees_id_key', 'employee', ['id'])
    op.drop_index(op.f('ix_employee_work_start'), table_name='employee')
    op.drop_index(op.f('ix_employee_salary'), table_name='employee')
    op.drop_index(op.f('ix_employee_position'), table_name='employee')
    op.drop_index(op.f('ix_employee_manager_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_full_name'), table_name='employee')
    op.alter_column('employee', 'full_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
